# Generated by Django 2.2 on 2019-05-09 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
