# Generated by Django 2.2 on 2019-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0004_auto_20190510_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('members', models.IntegerField(default=0)),
                ('carbon_points', models.FloatField(default=0.0)),
                ('dollar_savings', models.FloatField(default=0.0)),
            ],
        ),
    ]
